/**
 * Islands SSR Plugin
 *
 * Implements the SSRPlugin interface to add islands architecture support:
 * - Selective hydration via client:* directives
 * - Signal state tracking and serialization for island components
 * - Client-side deferred hydration strategies (load, idle, visible, media, only)
 *
 * Async streaming is handled by the core server-renderer. This plugin augments
 * the streamed replacements with island-specific data (signal state, hydration info)
 * via the `onAsyncComponentResolved` hook.
 *
 * @example
 * ```ts
 * import { createSSR } from '@sigx/server-renderer';
 * import { islandsPlugin } from '@sigx/ssr-islands';
 *
 * const ssr = createSSR().use(islandsPlugin());
 * const html = await ssr.render(<App />);
 * ```
 */

import type { SSRPlugin } from '@sigx/server-renderer';
import type { SSRContext } from '@sigx/server-renderer';
import type { VNode, ComponentSetupContext } from 'sigx';
import { signal } from 'sigx';
import {
    getHydrationDirective,
    filterClientDirectives,
    serializeProps,
} from 'sigx/internals';

import { createTrackingSignal, serializeSignalState } from './server/render-component';
import {
    generateIslandDataScript,
    escapeJsonForScript
} from './server/render-islands';
import type { IslandInfo, HydrationStrategy } from './types';

import {
    scheduleComponentHydration,
    hydrateIslands,
    initIslandHydration
} from './client/hydrate-islands';
import { hydrateLeftoverAsyncComponents } from './client/hydrate-async';
import { getIslandServerState } from './client/island-context';

// ─── Plugin Data Types ──────────────────────────────────────────

interface IslandsPluginData {
    islands: Map<number, IslandInfo>;
    /** Per-component signal maps, keyed by component ID */
    signalMaps: Map<number, Map<string, any>>;
}

const PLUGIN_NAME = 'islands';

// ─── Plugin Options ─────────────────────────────────────────────

export interface IslandsPluginOptions {
    /**
     * Custom hydration strategies (client-side only).
     * Keys are strategy names, values are scheduling functions.
     */
    strategies?: Record<string, (el: Element, hydrate: () => void) => void>;

    /**
     * Island manifest mapping component names to their chunk URLs.
     * Generated by `sigxIslandsPlugin()` from `@sigx/vite` during build.
     *
     * When provided, each island's `chunkUrl` and `exportName` will be set
     * in the `__SIGX_ISLANDS__` data, enabling the client to load chunks
     * on-demand without requiring eager `registerComponent()` calls.
     *
     * @example
     * ```ts
     * import manifest from './dist/island-manifest.json';
     * const ssr = createSSR().use(islandsPlugin({ manifest }));
     * ```
     */
    manifest?: Record<string, { chunkUrl: string; exportName: string }>;
}

// ─── Plugin Implementation ──────────────────────────────────────

/**
 * Create an islands SSR plugin.
 *
 * Server-side: intercepts components with `client:*` directives, tracks signal state,
 * manages async streaming, and injects `__SIGX_ISLANDS__` hydration data.
 *
 * Client-side: intercepts components with `client:*` during hydration walk,
 * schedules deferred hydration, and handles async component streaming.
 */
export function islandsPlugin(options?: IslandsPluginOptions): SSRPlugin {
    return {
        name: PLUGIN_NAME,

        server: {
            setup(ctx: SSRContext) {
                ctx.setPluginData<IslandsPluginData>(PLUGIN_NAME, {
                    islands: new Map(),
                    signalMaps: new Map()
                });
            },

            transformComponentContext(
                ctx: SSRContext,
                vnode: VNode,
                componentCtx: ComponentSetupContext
            ): ComponentSetupContext | void {
                const allProps = vnode.props || {};
                const hydration = getHydrationDirective(allProps);

                if (!hydration) return; // Not an island — don't touch

                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME)!;
                const componentName = (vnode.type as any).__islandId || (vnode.type as any).__name || 'Anonymous';

                // Get the component ID (already assigned by core renderer)
                const id = ctx._componentStack[ctx._componentStack.length - 1];

                // Filter client:* directives from props
                const { children, slots: slotsFromProps, $models: modelsData, ...propsData } = filterClientDirectives(allProps);

                // Register this island
                const islandInfo: IslandInfo = {
                    strategy: hydration.strategy as HydrationStrategy,
                    media: hydration.media,
                    props: serializeProps(propsData),
                    componentId: componentName
                };

                // Attach chunk URL from manifest if available
                if (options?.manifest && componentName in options.manifest) {
                    const entry = options.manifest[componentName];
                    islandInfo.chunkUrl = entry.chunkUrl;
                    islandInfo.exportName = entry.exportName;
                }

                data.islands.set(id, islandInfo);

                // Set up signal tracking for state serialization
                const signalMap = new Map<string, any>();
                data.signalMaps.set(id, signalMap);

                // Swap signal function with tracking variant
                componentCtx.signal = createTrackingSignal(signalMap) as typeof signal;
                componentCtx._signals = signalMap;

                return componentCtx;
            },

            afterRenderComponent(
                id: number,
                vnode: VNode,
                html: string,
                ctx: SSRContext
            ): string | void {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data) return;

                const islandInfo = data.islands.get(id);
                if (!islandInfo) return; // Not an island

                // For client:only, replace content with empty placeholder
                if (islandInfo.strategy === 'only') {
                    return `<div data-island="${id}"></div>`;
                }

                // Capture signal state
                const signalMap = data.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        islandInfo.state = state;
                    }
                }

                // Return html as-is (core already wraps with <!--$c:N-->)
                return;
            },

            handleAsyncSetup(
                id: number,
                ssrLoads: Promise<void>[],
                renderFn: () => any,
                ctx: SSRContext
            ): { mode: 'block' | 'stream' | 'skip'; placeholder?: string } | void {
                // Islands plugin no longer manages deferred renders.
                // Core handles async streaming; we just augment via onAsyncComponentResolved.
                // Return void to accept core's default (stream in streaming mode, block otherwise).
                return;
            },

            onAsyncComponentResolved(
                id: number,
                html: string,
                ctx: SSRContext
            ): { html?: string; script?: string } | void {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data) return;

                const islandInfo = data.islands.get(id);
                if (!islandInfo) return; // Not an island — no augmentation needed

                // Capture final signal state after async data loaded
                const signalMap = data.signalMaps.get(id);
                if (signalMap && signalMap.size > 0) {
                    const state = serializeSignalState(signalMap);
                    if (state) {
                        islandInfo.state = state;
                    }
                }

                // Inject script that updates __SIGX_ISLANDS__ data for this component
                const islandJson = escapeJsonForScript(JSON.stringify(islandInfo));
                const script = `
                    var ds=document.getElementById('__SIGX_ISLANDS__');
                    if(ds){try{var d=JSON.parse(ds.textContent||'{}');d[${id}]=${islandJson};ds.textContent=JSON.stringify(d);}catch(e){}}
                `;

                return { script };
            },

            getInjectedHTML(ctx: SSRContext): string {
                const data = ctx.getPluginData<IslandsPluginData>(PLUGIN_NAME);
                if (!data || data.islands.size === 0) return '';

                const islandData: Record<number, IslandInfo> = {};
                data.islands.forEach((info, id) => {
                    islandData[id] = info;
                });

                return generateIslandDataScript(islandData);
            }
        },

        client: {
            hydrateComponent(
                vnode: VNode,
                dom: Node | null,
                parent: Node
            ): Node | null | undefined {
                const strategy = vnode.props ? getHydrationDirective(vnode.props) : null;

                if (!strategy) return undefined; // Not an island — let core handle it

                return scheduleComponentHydration(vnode, dom, parent, strategy);
            },

            afterHydrate(container: Element): void {
                hydrateLeftoverAsyncComponents(container);
            }
        }
    };
}
